# Generated by Django 5.1.1 on 2024-12-05 06:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumerosComprados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_comprado', models.PositiveIntegerField()),
                ('nombre_persona', models.CharField(max_length=50, verbose_name='Nombre del comprador')),
                ('apellido_persona', models.CharField(max_length=50, verbose_name='Apellido del comprador')),
                ('telefono_persona', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefono del comprador')),
                ('correo_persona', models.CharField(blank=True, max_length=50, null=True, verbose_name='Correo del comprador')),
                ('estado_compra_numero', models.CharField(choices=[('pagado', 'PAGADO'), ('reservado', 'RESERVADO')], default='reservado', max_length=50, verbose_name='Estado de compra del número')),
            ],
        ),
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rifa', models.CharField(max_length=200, verbose_name='Nombre de Rifa')),
                ('descripcion_rifa', models.CharField(max_length=1000, verbose_name='Descripcion de Rifa')),
                ('cantidad_numeros', models.PositiveIntegerField(verbose_name='Cantidad de números de la rifa')),
                ('fecha_inicio_rifa', models.DateField(verbose_name='Fecha de inicio de rifa')),
                ('fecha_termino_rifa', models.DateField(verbose_name='Fecha de termino de rifa')),
                ('imagen_logo_rifa', models.ImageField(upload_to='static/images/Logos_rifa')),
                ('estado_rifa', models.CharField(choices=[('oculta', 'Oculta'), ('disponible', 'Disponible'), ('finalizada', 'Finalizada'), ('anulada', 'Anulada')], default='Disponible', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ganador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ganador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del ganador')),
                ('apellido_ganador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido del ganador')),
                ('telefono_ganador', models.CharField(blank=True, max_length=14, null=True, verbose_name='Teléfono del ganador')),
                ('correo_ganador', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo electrónico del ganador')),
                ('fecha_ganador', models.DateField(default=datetime.date.today, verbose_name='Fecha del premio')),
                ('numero_comprado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RifaSolidaria.numeroscomprados', verbose_name='Número ganador')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RifaSolidaria.rifa', verbose_name='Rifa asociada')),
            ],
        ),
        migrations.CreateModel(
            name='PremiosRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_premio_rifa', models.ImageField(upload_to='static/images/Premios_rifa')),
                ('nombre_premio', models.CharField(max_length=300, verbose_name='Nombre del premio')),
                ('descripcion_premio', models.CharField(max_length=500, verbose_name='Descripción de premio')),
                ('premio_mayor', models.BooleanField(default=False, verbose_name='Premio Mayor')),
                ('ganador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RifaSolidaria.ganador', verbose_name='Ganador')),
                ('nombre_rifa_premios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RifaSolidaria.rifa')),
            ],
        ),
        migrations.AddField(
            model_name='numeroscomprados',
            name='rifa_participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RifaSolidaria.rifa'),
        ),
    ]
